# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IU6r5/1FpZkR6VeOyZRn2lT4VhqOcVoawFrv5jKzbc+hgPSaeT1R71ekig8g9gk4fBGtuqCE3B4/z8w5NVpLhgNhnrAJ2SH7uKIZT6IdlMMft6qHO1/1JNbus6giosgrqcckQ6oS68OVlQgHiEmHWZ1B5LUxjf08tZNLmMOPVZUcxwKojyDgp9xxQxt6AWgDEgUgBI6Cb9c6tlt2LVQQ1Wf4jmiKWu26LTilhNPW90VR4U5xG3pcy5JArBCza5sRG9lHNg7Su+VBrYh5d06o3daVedK2iit4GajewxQ7Owiv53f1ancgYcmkSOjTtbyPaB+uGQ1hxzyv8HmJbgOw9q0+DqDxkEKuTCfHTRch+EIuTzBWLL9wDLYeXW8AYgT88pnPkQHEuseJa+s5Q5h0pkQ4oZ1tc7rtHTWzw78xc02wN0XiDIuIDMXMxD5OhAcSLOsC5+wdeXqwUTzFulEHR3psdDSB847ONXWE2++7LjIVBDx3kyBwo3Ic8pdCI3f70KR5Zzd1tSqZkIebLFk1f2Ga7+dVvfq9QswDJYherP9Z4tz6RUpqAx0lZ7+ltykyme79OrGJX6Od982j+nOavnrT+mpu8mH0/elLb/zlaTnGf1C/1jgvEsis5MUZlfaRE6AsOl3Yk3AtMNeR1zUt0x2qdrkOuFw8z4n+/uQsNzw="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi